version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      java: corretto11
  pre_build:
    on-failure: ABORT
    commands:
    - mvn clean
    - mvn validate
    - echo Pre-build completed on 'data'
  build:
    on-failure: ABORT
    commands:
    - echo Build completed on date
    - mvn compile
    - mvn test
  post_build:
    on-failure: ABORT
    commands:
    - echo Build completed on date
    - mvn package
    - cp target/*.jar ROOT.jar
artifacts:
  files:
  - ROOT.jar
  name: sample-java-artifact
  